server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 20MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
          predicates:
            - Path=/auth/**
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL:http://profile-service:8082}
          predicates:
            - Path=/profiles/**
        - id: profile-files
          uri: ${PROFILE_SERVICE_URL:http://profile-service:8082}
          predicates:
            - Path=/files/**
        - id: jobs-service
          uri: ${JOBS_SERVICE_URL:http://jobs-service:8083}
          predicates:
            - Path=/jobs/**
        - id: matching-service
          uri: ${MATCHING_SERVICE_URL:http://matching-service:8084}
          predicates:
            - Path=/matching/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8085}
          predicates:
            - Path=/ws-notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
