version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: catch-and-go-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catchgo-network

  redis:
    image: redis:7-alpine
    container_name: catch-and-go-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - catchgo-network

volumes:
  postgres_data:

networks:
  catchgo-network:
    driver: bridge
