version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: catchgo-postgres
    restart: always
    environment:
      POSTGRES_USER: catchgo_admin
      POSTGRES_PASSWORD: admin_password_123
      POSTGRES_DB: catchgo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catchgo-network

  redis-cache:
    image: redis:7-alpine
    container_name: catchgo-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - catchgo-network

volumes:
  postgres_data:


networks:
  catchgo-network:
    driver: bridge
