server:
  port: ${PORT:${SERVER_PORT:8085}}

spring:
  application:
    name: notification-service
  data:
    redis:
      host: ${REDISHOST:${REDIS_HOST:localhost}}
      port: ${REDISPORT:${REDIS_PORT:6379}}
      password: ${REDISPASSWORD:${REDIS_PASSWORD:}}
      timeout: 5000ms
      connect-timeout: 5000ms

logging:
  level:
    com.catchandgo: DEBUG

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
