CREATE TABLE IF NOT EXISTS job_offers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

ALTER TABLE job_offers 
ADD COLUMN IF NOT EXISTS titulo VARCHAR(255) NOT NULL DEFAULT 'Sin Título',
ADD COLUMN IF NOT EXISTS descripcion TEXT,
ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(255),
ADD COLUMN IF NOT EXISTS remuneracion INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fecha_inicio VARCHAR(50),
ADD COLUMN IF NOT EXISTS fecha_fin VARCHAR(50),
ADD COLUMN IF NOT EXISTS estado VARCHAR(50) DEFAULT 'ABIERTA',
ADD COLUMN IF NOT EXISTS empresa_id BIGINT;

