ALTER TABLE job_offers 
ADD COLUMN titulo VARCHAR(255) NOT NULL DEFAULT 'Sin Título',
ADD COLUMN descripcion TEXT,
ADD COLUMN ubicacion VARCHAR(255),
ADD COLUMN remuneracion INTEGER DEFAULT 0,
ADD COLUMN fecha_inicio VARCHAR(50),
ADD COLUMN fecha_fin VARCHAR(50),
ADD COLUMN estado VARCHAR(50) DEFAULT 'ABIERTA',
ADD COLUMN empresa_id BIGINT;
