# Puerto del Auth Service
server.port=8081
spring.application.name=auth-service

# Configuración de H2 Database (En memoria)
spring.datasource.url=jdbc:h2:mem:catchandgodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear tablas automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2 (Para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console