server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: jobs-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catchandgo}
    username: ${SPRING_DATASOURCE_USERNAME:catchandgo}
    password: ${SPRING_DATASOURCE_PASSWORD:catchandgo}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    repair-on-migrate: true
    validate-on-migrate: false
    table: flyway_schema_history_jobs
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
